-- Seed data for Orient Express menu
-- Sections: soupes | entrees | volailles | viandes | fruits-mer | riz-nouilles

INSERT INTO menu_items (num, section, display_order,
  name_fr, name_nl, name_en,
  description_fr, description_nl, description_en,
  price) VALUES

-- SOUPES
('S1', 'soupes', 10,
  'Soupe Wan Tan',
  'Wan Tan Soep',
  'Wan Tan Soup',
  'Raviolis aux crevettes et porc en bouillon',
  'Ravioli met garnalen en varkensvlees in bouillon',
  'Shrimp and pork dumplings in broth',
  6.50),

('S2', 'soupes', 20,
  'Soupe Pékinoise',
  'Pekingse Soep',
  'Peking Soup',
  'Bouillon relevé, tofu, champignons noirs, œuf',
  'Gekruide bouillon, tofu, zwarte champignons, ei',
  'Spiced broth, tofu, black mushrooms, egg',
  6.00),

('S3', 'soupes', 30,
  'Soupe Asperges et Crabe',
  'Asperge- en Krabbensoep',
  'Asparagus and Crab Soup',
  'Velouté délicat à la chair de crabe',
  'Delicate crèmesoep met krabvlees',
  'Delicate velouté with crab meat',
  7.00),

('S4', 'soupes', 40,
  'Soupe Saïgon',
  'Saigon Soep',
  'Saigon Soup',
  'Bouillon parfumé, scampis, viande, vermicelles',
  'Geurige bouillon, scampis, vlees, vermicelli',
  'Fragrant broth, prawns, meat, vermicelli',
  7.50),

-- ENTRÉES
('E1', 'entrees', 10,
  'Nems (4 pcs)',
  'Nems (4 st.)',
  'Spring Rolls (4 pcs)',
  'Rouleaux frits aux crevettes et légumes',
  'Gefrituurde rolletjes met garnalen en groenten',
  'Fried rolls with shrimp and vegetables',
  7.50),

('E2', 'entrees', 20,
  'Rouleaux de Printemps (2 pcs)',
  'Loempia''s (2 st.)',
  'Fresh Spring Rolls (2 pcs)',
  'Légumes frais, vermicelle, sauce aigre-douce',
  'Verse groenten, vermicelli, zoetzure saus',
  'Fresh vegetables, vermicelli, sweet and sour sauce',
  6.50),

('E3', 'entrees', 30,
  'Satay Poulet (4 brochettes)',
  'Kip Satay (4 stokjes)',
  'Chicken Satay (4 skewers)',
  'Brochettes de poulet grillées, sauce cacahuète',
  'Gegrilde kipspiesjes, pindanouissaus',
  'Grilled chicken skewers, peanut sauce',
  9.00),

('E4', 'entrees', 40,
  'Dim Sum Vapeur (6 pcs)',
  'Gestoomde Dim Sum (6 st.)',
  'Steamed Dim Sum (6 pcs)',
  'Bouchées vapeur au choix : poulet, scampis ou légumes',
  'Gestoomde hapjes: kip, scampis of groenten',
  'Steamed dumplings: chicken, prawns or vegetables',
  9.50),

('E5', 'entrees', 50,
  'Assiette Maison',
  'Huisgerechtschotel',
  'Chef''s Platter',
  'Assortiment d''entrées — min. 2 couverts',
  'Assortiment van voorgerechtjes — min. 2 personen',
  'Selection of starters — min. 2 persons',
  12.50),

('E6', 'entrees', 60,
  'Canard Laqué (crêpes)',
  'Pekingeend (pannenkoekjes)',
  'Peking Duck (pancakes)',
  'Canard rôti, crêpes mandarine, sauce hoisin',
  'Geroosterde eend, mandarijnpannenkoekjes, hoisinsaus',
  'Roasted duck, mandarin pancakes, hoisin sauce',
  14.00),

-- VOLAILLES
('V1', 'volailles', 10,
  'Poulet aux Noix de Cajou',
  'Kip met Cashewnoten',
  'Chicken with Cashew Nuts',
  'Poulet sauté, noix de cajou, légumes croquants',
  'Gebakken kip, cashewnoten, knapperige groenten',
  'Sautéed chicken, cashew nuts, crispy vegetables',
  13.50),

('V2', 'volailles', 20,
  'Poulet au Citron',
  'Kip met Citroen',
  'Lemon Chicken',
  'Poulet frit, sauce citron maison',
  'Gefrituurde kip, huisgemaakte citroensaus',
  'Fried chicken, homemade lemon sauce',
  13.00),

('V3', 'volailles', 30,
  'Poulet Piquant au Basilic',
  'Pittige Kip met Basilicum',
  'Spicy Basil Chicken',
  'Sauté au wok avec piment et basilic thaï',
  'Wok-gebakken met peper en Thaise basilicum',
  'Wok-fried with chilli and Thai basil',
  13.50),

('V4', 'volailles', 40,
  'Canard à l''Orange',
  'Eend met Sinaasappel',
  'Duck à l''Orange',
  'Canard rôti, sauce à l''orange maison',
  'Geroosterde eend, huisgemaakte sinaasappelsaus',
  'Roasted duck, homemade orange sauce',
  16.00),

('V5', 'volailles', 50,
  'Poulet aux 3 Champignons',
  'Kip met 3 Champignons',
  'Chicken with 3 Mushrooms',
  'Shiitake, pleurotes et champignons noirs',
  'Shiitake, oesterzwammen en zwarte champignons',
  'Shiitake, oyster mushrooms and black mushrooms',
  14.00),

-- VIANDES
('M1', 'viandes', 10,
  'Bœuf aux Brocolis',
  'Rund met Broccoli',
  'Beef with Broccoli',
  'Bœuf sauté au wok, brocolis, sauce huître',
  'Wok-gebakken rund, broccoli, oestersaus',
  'Wok-fried beef, broccoli, oyster sauce',
  14.00),

('M2', 'viandes', 20,
  'Bœuf Piquant au Poivre Noir',
  'Pittig Rund met Zwarte Peper',
  'Spicy Black Pepper Beef',
  'Émincé de bœuf, sauce poivre noir, légumes',
  'Gesneden rund, zwartepepersaus, groenten',
  'Sliced beef, black pepper sauce, vegetables',
  14.50),

('M3', 'viandes', 30,
  'Porc Sauce Aigre-Douce',
  'Varken in Zoetzure Saus',
  'Sweet and Sour Pork',
  'Porc pané, sauce aigre-douce aux légumes',
  'Gepaneerd varken, zoetzure saus met groenten',
  'Battered pork, sweet and sour sauce with vegetables',
  13.00),

('M4', 'viandes', 40,
  'Porc Laqué au Miel',
  'Honinglak Varken',
  'Honey Glazed Pork',
  'Caramélisé au miel et sésame',
  'Gekarameliseerd met honing en sesam',
  'Caramelised with honey and sesame',
  13.50),

('M5', 'viandes', 50,
  'Les 8 Délices',
  'De 8 Lekkernijen',
  'Eight Treasures',
  'Porc, poulet, scampis, calamars, légumes variés',
  'Varken, kip, scampis, inktvis, diverse groenten',
  'Pork, chicken, prawns, squid, mixed vegetables',
  16.00),

-- FRUITS DE MER
('F1', 'fruits-mer', 10,
  'Scampis à l''Ail',
  'Knoflookgarnalen',
  'Garlic Prawns',
  'Scampis sautés à l''ail et beurre de persil',
  'Gebakken scampis met knoflook en peterselieroom',
  'Sautéed prawns with garlic and parsley butter',
  16.50),

('F2', 'fruits-mer', 20,
  'Calamars Croquants',
  'Knapperige Inktvis',
  'Crispy Squid',
  'Calamars frits, sauce sweet chili',
  'Gefrituurde inktvis, zoete chilisaus',
  'Fried squid, sweet chilli sauce',
  14.00),

('F3', 'fruits-mer', 30,
  'Marmite du Pêcheur',
  'Visserspot',
  'Fisherman''s Pot',
  'St-Jacques, scampis, calamars, poisson du jour',
  'Sint-jakobsschelpen, scampis, inktvis, dagverse vis',
  'Scallops, prawns, squid, fish of the day',
  19.00),

('F4', 'fruits-mer', 40,
  'Saumon au Gingembre',
  'Zalm met Gember',
  'Ginger Salmon',
  'Filet de saumon, sauce gingembre et citron',
  'Zalmfilet, gember- en citroensaus',
  'Salmon fillet, ginger and lemon sauce',
  16.00),

-- RIZ & NOUILLES
('R1', 'riz-nouilles', 10,
  'Riz Sauté Légumes',
  'Roergebakken Rijst Groenten',
  'Vegetable Fried Rice',
  'Végétarien',
  'Vegetarisch',
  'Vegetarian',
  10.50),

('R2', 'riz-nouilles', 20,
  'Riz Sauté Poulet',
  'Roergebakken Rijst Kip',
  'Chicken Fried Rice',
  'Riz parfumé sauté au wok avec poulet',
  'Geurige rijst wok-gebakken met kip',
  'Fragrant rice wok-fried with chicken',
  11.50),

('R3', 'riz-nouilles', 30,
  'Riz Sauté Special Mix',
  'Roergebakken Rijst Special Mix',
  'Special Mixed Fried Rice',
  'Poulet, scampis, porc et légumes',
  'Kip, scampis, varken en groenten',
  'Chicken, prawns, pork and vegetables',
  13.00),

('R4', 'riz-nouilles', 40,
  'Nouilles Sautées Poulet',
  'Roergebakken Noedels Kip',
  'Chicken Fried Noodles',
  'Nouilles de blé sautées au wok',
  'Tarwenoedels wok-gebakken',
  'Wheat noodles wok-fried',
  11.50),

('R5', 'riz-nouilles', 50,
  'Nouilles Sautées Scampis',
  'Roergebakken Noedels Scampis',
  'Prawn Fried Noodles',
  'Nouilles de blé sautées aux scampis',
  'Tarwenoedels wok-gebakken met scampis',
  'Wheat noodles wok-fried with prawns',
  13.00),

('R6', 'riz-nouilles', 60,
  'Grande Soupe Pho',
  'Grote Pho Soep',
  'Large Pho Soup',
  'Bouillon de bœuf maison, nouilles de riz, herbes',
  'Huisgemaakte runderbouillon, rijstnoedels, kruiden',
  'Homemade beef broth, rice noodles, fresh herbs',
  13.50);
